// <auto-generated />
namespace JQueryAjaxCRUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nameofficeandsalaryrequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nameofficeandsalaryrequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201906021331555_name, office and salary required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
